<template>
  <p>MAP</p>
  <br />
  <div class="image-map">
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="../assets/landmap2.jpg" usemap="#image-map" />
    <map name="image-map">
      <area
        target=""
        alt="michelle's house"
        title="michelle's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_1"
        coords="400,469,18"
        shape="circle"
      />
      <area
        target=""
        alt="tont's house"
        title="tont's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_2"
        coords="422,659,17"
        shape="circle"
      />
      <area
        target=""
        alt="gulley's house"
        title="gulley's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_3"
        coords="256,663,17"
        shape="circle"
      />
      <area
        target=""
        alt="ben's house"
        title="ben's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_4"
        coords="153,583,19"
        shape="circle"
      />
      <area
        target=""
        alt="Li's house"
        title="Li's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_5"
        coords="237,493,18"
        shape="circle"
      />
      <area
        target=""
        alt="Thiago's house"
        title="Thiago's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_6"
        coords="306,351,19"
        shape="circle"
      />
      <area
        target=""
        alt="Isabella's house"
        title="Isabella's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_7"
        coords="445,252,18"
        shape="circle"
      />
      <area
        target=""
        alt="Emilia's house"
        title="Emilia's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_8"
        coords="379,156,18"
        shape="circle"
      />
      <area
        target=""
        alt="Chioma's house"
        title="Chioma's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_9"
        coords="195,200,17"
        shape="circle"
      />
      <area
        target=""
        alt="Alexander's house"
        title="Alexander's house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/home_10"
        coords="158,157,20"
        shape="circle"
      />
      <area
        target=""
        alt="Ocean restaurant"
        title="Ocean restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_1"
        coords="273,526,21"
        shape="circle"
      />
      <area
        target=""
        alt="Olive Kitchen restaurant"
        title="Olive Kitchen restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_2"
        coords="435,492,19"
        shape="circle"
      />
      <area
        target=""
        alt="Baga Burgar restaurant"
        title="Baga Burgar restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_3"
        coords="337,469,20"
        shape="circle"
      />
      <area
        target=""
        alt="Seizeria restaurant"
        title="Seizeria restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_4"
        coords="309,407,21"
        shape="circle"
      />
      <area
        target=""
        alt="akki restaurant"
        title="akki restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_5"
        coords="171,445,20"
        shape="circle"
      />
      <area
        target=""
        alt="XAN Curry restaurant"
        title="XAN Curry restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_6"
        coords="155,365,18"
        shape="circle"
      />
      <area
        target=""
        alt="Pizza bAd restaurant"
        title="Pizza bAd restaurant"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/store_7"
        coords="280,319,19"
        shape="circle"
      />
      <area
        target=""
        alt="LyCa mobile"
        title="LyCa mobile"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/phone_rental"
        coords="506,656,35"
        shape="circle"
      />
      <area
        target=""
        alt="yamaguchi drug"
        title="yamaguchi drug"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/medical"
        coords="669,512,31"
        shape="circle"
      />
      <area
        target=""
        alt="yamaguchi drug"
        title="yamaguchi drug"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/medical"
        coords="216,288,30"
        shape="circle"
      />
      <area
        target=""
        alt="airport portal"
        title="airport portal"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/airport"
        coords="954,461,30"
        shape="circle"
      />
      <area
        target=""
        alt="White Ferris Wheel"
        title="White Ferris Wheel"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/ferris_wheel"
        coords="764,171,85"
        shape="circle"
      />
      <area
        target=""
        alt="White Ferris Wheel"
        title="White Ferris Wheel"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/ferris_wheel"
        coords="818,285,712,224"
        shape="rect"
      />
      <area
        target=""
        alt="Warehouse"
        title="Warehouse"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/warehouse"
        coords="864,154,953,225"
        shape="rect"
      />
      <area
        target=""
        alt="Souvenir house"
        title="Souvenir house"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/souvenir"
        coords="306,572,443,622"
        shape="rect"
      />
      <area
        target=""
        alt="Snack factory"
        title="Snack factory"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/factory"
        coords="611,572,795,679"
        shape="rect"
      />
      <area
        target=""
        alt="Central Saint Dogma Park"
        title="Central Saint Dogma Park"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/central_park"
        coords="462,365,35"
        shape="circle"
      />
      <area
        target=""
        alt="Five STAR hotel"
        title="Five STAR hotel"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/hotel"
        coords="762,435,845,495"
        shape="rect"
      />
      <area
        target=""
        alt="Park"
        title="Park"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/park"
        coords="488,530,491,562,601,546,653,426,616,374,537,384,490,407,468,431,472,531,480,530"
        shape="poly"
      />
      <area
        target=""
        alt="nation station"
        title="nation station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_nation"
        coords="169,640,14"
        shape="circle"
      />
      <area
        target=""
        alt="citi station"
        title="citi station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_citi"
        coords="228,392,13"
        shape="circle"
      />
      <area
        target=""
        alt="maxwell station"
        title="maxwell station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_maxwell"
        coords="328,165,15"
        shape="circle"
      />
      <area
        target=""
        alt="minwell station"
        title="minwell station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_minwell"
        coords="948,240,13"
        shape="circle"
      />
      <area
        target=""
        alt="airportal station"
        title="airportal station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_airportal"
        coords="897,480,14"
        shape="circle"
      />
      <area
        target=""
        alt="eternal station"
        title="eternal station"
        @mouseover="contentsVisible"
        @mouseleave="contentsInvisible"
        href="/contents/station_eternal"
        coords="928,641,22"
        shape="circle"
      />
    </map>
    <!-- <p id="p_map_content">details will be shown</p> -->
    <p id="home_1">This is Michelle's house. They are throwing a party, let's join!</p>
    <p id="home_2">This is Tont's house. They are currently out.</p>
    <p id="home_3">This is Gulley's house. A lot of games are available here.</p>
    <p id="home_4">This is Ben's house. They are throwing a party, let's join!</p>
    <p id="home_5">This is Li's house. They are currently out.</p>
    <p id="home_6">This is Thiago's house. A lot of games are available here.</p>
    <p id="home_7">This is Isabella's house. They are throwing a party, let's join!</p>
    <p id="home_8">This is Emilia's house. They are currently out.</p>
    <p id="home_9">This is Chioma's house. A lot of games are available here.</p>
    <p id="home_10">This is Alexander's house. They are throwing a party, let's join!</p>

    <p id="store_1">This is Ocean restaurant. Enjoy the sea breeze with your meal!</p>
    <p id="store_2">This is Olive Kitchen restaurant. A taste of the Mediterranean awaits!</p>
    <p id="store_3">This is Baga Burgar restaurant. Home of the juiciest burgers in town!</p>
    <p id="store_4">This is Seizeria restaurant. Where affordability meets Italian cuisine!</p>
    <p id="store_5">This is aki restaurant. Traditional flavors in a modern setting!</p>
    <p id="store_6">This is XAN Curry restaurant. Spices and everything nice!</p>
    <p id="store_7">This is Pizza bAd restaurant. Where the pizza is as unique as its name!</p>

    <p id="phone_rental">
      This is Lyca mobile.Rent a smartphone for use inside the museum. One per person, rental is
      free.
    </p>
    <p id="station_nation">
      This is nation station.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
    <p id="souvenir">
      This is Souvenir house.This is where you can buy souvenirs. Be sure to visit during your
      museum trip!
    </p>
    <p id="medical">
      This is yamaguchi drug. If you're feeling unwell, come here for free necessary treatments.
    </p>
    <p id="ferris_wheel">
      This is White Ferris Wheel.View the museum from the 80m high ferris wheel! An additional fee
      of 5 euros per person applies.
    </p>
    <p id="warehouse">This is Warehouse.</p>
    <p id="factory">This is Snack factory. You can watch robots at work!</p>
    <p id="center_park">This is Central Saint Dogma Park.</p>
    <p id="hotel">
      This is Five STAR hotel.Learn about the history of gaming and the computer science technology
      used here!
    </p>
    <p id="park">This is Park.</p>

    <p id="station_citi">
      This is cit station.Packed with collaborations with manufacturers and vehicles you can't see
      anywhere else!
    </p>
    <p id="station_maxwell">
      This is maxwell station.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
    <p id="station_minwell">
      This is minwell station.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
    <p id="station_airportal">
      This is airportal station.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
    <p id="station_eternal">
      This is eternal station.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
    <p id="airport">
      This is airport portal.Packed with collaborations with manufacturers and vehicles you can't
      see anywhere else!
    </p>
  </div>
  <br />
  <br />
</template>

<script>
export default {
  name: 'MapView',
  methods: {
    contentsVisible(event) {
      const p_element_text = event.target.href.split('/')[4].replace('map#', '')
      // console.log('p_element_text', p_element_text)
      const p_element = document.getElementById(p_element_text)
      if (p_element === null) {
        console.error('Cannot find id element: ', p_element_text)
      } else {
        p_element.classList.add('contents-visible')
      }
    },
    contentsInvisible(event) {
      const p_element_text = event.target.href.split('/')[4].replace('map#', '')
      const p_element = document.getElementById(p_element_text)
      if (p_element === null) {
        console.error('Cannot find id element: ', p_element_text)
      } else {
        p_element.classList.remove('contents-visible')
      }
    }
  }
}
</script>

<style>
p {
  color: white;
}

#img_title {
  margin-left: 0;
  /* margin-right: 0; */
  margin-bottom: 0.1em;
}

.image-map div {
  margin-bottom: 0.1em;
}

.image-map p {
  display: none;
}

.contents-visible {
  display: block !important;
}
</style>
